
package com.chubb.workview.policyservice._2016._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PolicyService", targetNamespace = "http://Chubb.WorkView.ServiceContracts/2009/06")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PolicyService {


    /**
     * 
     * @param request
     * @return
     *     returns com.ace.dtsi.integration.jaxb.Response
     */
    @WebMethod(operationName = "CreateOrUpdatePolicy", action = "http://chubb.com/WorkView/PolicyService/2016/06/PolicyService/CreateOrUpdatePolicy")
    @WebResult(name = "CreateOrUpdatePolicyResult", targetNamespace = "http://chubb.com/WorkView/PolicyService/2016/06")
    @RequestWrapper(localName = "CreateOrUpdatePolicy", targetNamespace = "http://chubb.com/WorkView/PolicyService/2016/06", className = "com.chubb.workview.policy._2016._06.CreateOrUpdatePolicyElement")
    @ResponseWrapper(localName = "CreateOrUpdatePolicyResponse", targetNamespace = "http://chubb.com/WorkView/PolicyService/2016/06", className = "com.chubb.workview.policy._2016._06.CreateOrUpdatePolicyResponseElement")
    public Response createOrUpdatePolicy(
        @WebParam(name = "request", targetNamespace = "http://chubb.com/WorkView/PolicyService/2016/06")
        Request request);


}
