package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import core.documentservice.chubb.IDocument;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-22T11:12:47.917+01:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "Document",
                  wsdlLocation = "https://uk01deca021.aceins.com:4466/DocumentService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class Document extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "Document");
    public final static QName WsHttpEndpoint = new QName("http://tempuri.org/", "wsHttpEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("https://uk01deca021.aceins.com:4466/DocumentService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Document.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://uk01deca021.aceins.com:4466/DocumentService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Document(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Document(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Document() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Document(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Document(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Document(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IDocument
     */
    @WebEndpoint(name = "wsHttpEndpoint")
    public IDocument getWsHttpEndpoint() {
        return super.getPort(WsHttpEndpoint, IDocument.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDocument
     */
    @WebEndpoint(name = "wsHttpEndpoint")
    public IDocument getWsHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(WsHttpEndpoint, IDocument.class, features);
    }

}
