
package com.chubb.workview.generalfileservice._2016._06;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GeneralFile", targetNamespace = "http://Chubb.com/WorkView/GeneralFile/2016/06", wsdlLocation = "https://uk01deca021.aceins.com:501/WorkView/GeneralFiles/GeneralFiles.svc?singlewsdl")
public class GeneralFile_Service
    extends Service
{

    private final static URL GENERALFILE_WSDL_LOCATION;
    private final static WebServiceException GENERALFILE_EXCEPTION;
    private final static QName GENERALFILE_QNAME = new QName("http://Chubb.com/WorkView/GeneralFile/2016/06", "GeneralFile");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://uk01deca021.aceins.com:501/WorkView/GeneralFiles/GeneralFiles.svc?singlewsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERALFILE_WSDL_LOCATION = url;
        GENERALFILE_EXCEPTION = e;
    }

    public GeneralFile_Service() {
        super(__getWsdlLocation(), GENERALFILE_QNAME);
    }

    public GeneralFile_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERALFILE_QNAME, features);
    }

    public GeneralFile_Service(URL wsdlLocation) {
        super(wsdlLocation, GENERALFILE_QNAME);
    }

    public GeneralFile_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERALFILE_QNAME, features);
    }

    public GeneralFile_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneralFile_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
    @WebEndpoint(name = "WSHttpBinding_GeneralFile")
    public GeneralFile getWSHttpBindingGeneralFile() {
        return super.getPort(new QName("http://Chubb.com/WorkView/GeneralFile/2016/06", "WSHttpBinding_GeneralFile"), GeneralFile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsuredService
     */
    @WebEndpoint(name = "WSHttpBinding_GeneralFile")
    public GeneralFile getWSHttpBindingGeneralFile(WebServiceFeature... features) {
        return super.getPort(new QName("http://Chubb.com/WorkView/GeneralFile/2016/06", "WSHttpBinding_GeneralFile"), GeneralFile.class, features);
    }
   
    private static URL __getWsdlLocation() {
        if (GENERALFILE_EXCEPTION!= null) {
            throw GENERALFILE_EXCEPTION;
        }
        return GENERALFILE_WSDL_LOCATION;
    }

}
