
package com.chubb.workview.insuredservice._2016._06;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsuredService", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", wsdlLocation = "https://wvuat-cogr2-iws-446.aceins.com:446/WorkView/InsuredService/InsuredService.svc?wsdl")
public class InsuredService_Service
    extends Service
{

    private final static URL INSUREDSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSUREDSERVICE_EXCEPTION;
    private final static QName INSUREDSERVICE_QNAME = new QName("http://Chubb.com/WorkView/InsuredService/2016/06", "InsuredService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://wvuat-cogr2-iws-446.aceins.com:446/WorkView/InsuredService/InsuredService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSUREDSERVICE_WSDL_LOCATION = url;
        INSUREDSERVICE_EXCEPTION = e;
    }

    public InsuredService_Service() {
        super(__getWsdlLocation(), INSUREDSERVICE_QNAME);
    }

    public InsuredService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSUREDSERVICE_QNAME, features);
    }

    public InsuredService_Service(URL wsdlLocation) {
        super(wsdlLocation, INSUREDSERVICE_QNAME);
    }

    public InsuredService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSUREDSERVICE_QNAME, features);
    }

    public InsuredService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsuredService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InsuredService
     */
    @WebEndpoint(name = "WSHttpBinding_InsuredService")
    public InsuredService getWSHttpBindingInsuredService() {
        return super.getPort(new QName("http://Chubb.com/WorkView/InsuredService/2016/06", "WSHttpBinding_InsuredService"), InsuredService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsuredService
     */
    @WebEndpoint(name = "WSHttpBinding_InsuredService")
    public InsuredService getWSHttpBindingInsuredService(WebServiceFeature... features) {
    	
        return super.getPort(new QName("http://Chubb.com/WorkView/InsuredService/2016/06", "WSHttpBinding_InsuredService"), InsuredService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSUREDSERVICE_EXCEPTION!= null) {
            throw INSUREDSERVICE_EXCEPTION;
        }
        return INSUREDSERVICE_WSDL_LOCATION;
    }

}
