
package com.chubb.workview.insuredservice._2016._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InsuredService", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InsuredService {


    /**
     * 
     * @param request
     * @return
     *     returns com.chubb.workview.preprocessors.generated.InsuredService.Response
     */
    @WebMethod(operationName = "CreateOrUpdateInsured", action = "http://Chubb.com/WorkView/InsuredService/2016/06/InsuredService/CreateOrUpdateInsured")
    @WebResult(name = "CreateOrUpdateInsuredResult", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
    @RequestWrapper(localName = "CreateOrUpdateInsured", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.insuredservice._2016._06.CreateOrUpdateInsured")
    @ResponseWrapper(localName = "CreateOrUpdateInsuredResponse", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.insuredservice._2016._06.CreateOrUpdateInsuredResponse")
    public Response createOrUpdateInsured(
        @WebParam(name = "request", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
        Request request);

    /**
     * 
     * @param request
     * @return
     *     returns com.chubb.workview.preprocessors.generated.InsuredService.GetInsuredResponseDetails
     */
    @WebMethod(operationName = "GetInsured", action = "http://Chubb.com/WorkView/InsuredService/2016/06/InsuredService/GetInsured")
    @WebResult(name = "GetInsuredResult", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
    @RequestWrapper(localName = "GetInsured", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetInsuredMod")
    @ResponseWrapper(localName = "GetInsuredResponse", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetInsuredResponse")
    public GetInsuredResponseDetails getInsured(
        @WebParam(name = "request", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
        GetInsuredRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.chubb.workview.preprocessors.generated.InsuredService.ExtractInsuredResponse
     */
    @WebMethod(operationName = "GetInsuredBatch", action = "http://Chubb.com/WorkView/InsuredService/2016/06/InsuredService/GetInsuredBatch")
    @WebResult(name = "GetInsuredBatchResult", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
    @RequestWrapper(localName = "GetInsuredBatch", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetInsuredBatch")
    @ResponseWrapper(localName = "GetInsuredBatchResponse", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetInsuredBatchResponse")
    public ExtractInsuredResponse getInsuredBatch(
        @WebParam(name = "request", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
        ExtractInsuredRequest request);

    /**
     * 
     * @param extractRequest
     * @return
     *     returns com.chubb.workview.preprocessors.generated.InsuredService.MeridianExtractInsuredResponse
     */
    @WebMethod(operationName = "GetInsuredMeridianBatch", action = "http://Chubb.com/WorkView/InsuredService/2016/06/InsuredService/GetInsuredMeridianBatch")
    @WebResult(name = "GetInsuredMeridianBatchResult", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
    @RequestWrapper(localName = "GetInsuredMeridianBatch", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetInsuredMeridianBatch")
    @ResponseWrapper(localName = "GetInsuredMeridianBatchResponse", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetInsuredMeridianBatchResponse")
    public MeridianExtractInsuredResponse getInsuredMeridianBatch(
        @WebParam(name = "extractRequest", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
        ExtractInsuredRequest extractRequest);

    /**
     * 
     * @param extractRequest
     * @return
     *     returns com.chubb.workview.preprocessors.generated.InsuredService.MeridianInsuredExtractResponse
     */
    @WebMethod(operationName = "GetMeridianExtractInsured", action = "http://Chubb.com/WorkView/InsuredService/2016/06/InsuredService/GetMeridianExtractInsured")
    @WebResult(name = "GetMeridianExtractInsuredResult", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
    @RequestWrapper(localName = "GetMeridianExtractInsured", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetMeridianExtractInsured")
    @ResponseWrapper(localName = "GetMeridianExtractInsuredResponse", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.GetMeridianExtractInsuredResponse")
    public MeridianInsuredExtractResponse getMeridianExtractInsured(
        @WebParam(name = "extractRequest", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
        ExtractInsuredRequest extractRequest);

    /**
     * 
     * @param yearlyPremiumRequest
     * @return
     *     returns com.chubb.workview.preprocessors.generated.InsuredService.YearlyPremiumResponse
     */
    @WebMethod(operationName = "UpdateYearlyPremium", action = "http://Chubb.com/WorkView/InsuredService/2016/06/InsuredService/UpdateYearlyPremium")
    @WebResult(name = "UpdateYearlyPremiumResult", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
    @RequestWrapper(localName = "UpdateYearlyPremium", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.UpdateYearlyPremium")
    @ResponseWrapper(localName = "UpdateYearlyPremiumResponse", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.UpdateYearlyPremiumResponse")
    public YearlyPremiumResponse updateYearlyPremium(
        @WebParam(name = "yearlyPremiumRequest", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
        YearlyPremiumRequest yearlyPremiumRequest);

    /**
     * 
     * @param insuredRelationRequest
     * @return
     *     returns com.chubb.workview.preprocessors.generated.InsuredService.InsuredRelationResponse
     */
    @WebMethod(operationName = "CreateOrUpdateInsuredRelation", action = "http://Chubb.com/WorkView/InsuredService/2016/06/InsuredService/CreateOrUpdateInsuredRelation")
    @WebResult(name = "CreateOrUpdateInsuredRelationResult", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
    @RequestWrapper(localName = "CreateOrUpdateInsuredRelation", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.CreateOrUpdateInsuredRelation")
    @ResponseWrapper(localName = "CreateOrUpdateInsuredRelationResponse", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06", className = "com.chubb.workview.preprocessors.generated.InsuredService.CreateOrUpdateInsuredRelationResponse")
    public InsuredRelationResponse createOrUpdateInsuredRelation(
        @WebParam(name = "insuredRelationRequest", targetNamespace = "http://Chubb.com/WorkView/InsuredService/2016/06")
        InsuredRelationRequest insuredRelationRequest);

}
