
package core.documentservice.chubb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.tempuri.Document;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-22T11:12:47.621+01:00
 * Generated source version: 3.3.3
 *
 */
public final class IDocument_WsHttpEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Document");

    private IDocument_WsHttpEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Document.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Document ss = new Document(wsdlURL, SERVICE_NAME);
        IDocument port = ss.getWsHttpEndpoint();

        {
        System.out.println("Invoking transferDocument...");
        datacontracts.core.documentservice.chubb._2016._03.TransferDocumentRequest _transferDocument_transferDocumentRequest = new datacontracts.core.documentservice.chubb._2016._03.TransferDocumentRequest();
        javax.xml.bind.JAXBElement<java.lang.String> _transferDocument_transferDocumentRequestDestinationSystem = null;
        _transferDocument_transferDocumentRequest.setDestinationSystem(_transferDocument_transferDocumentRequestDestinationSystem);
        javax.xml.bind.JAXBElement<datacontracts.core.documentservice.chubb._2016._03.TransferDocumentRequest.InputReferenceData> _transferDocument_transferDocumentRequestInputReferenceData = null;
        _transferDocument_transferDocumentRequest.setInputReferenceData(_transferDocument_transferDocumentRequestInputReferenceData);
        javax.xml.bind.JAXBElement<java.lang.String> _transferDocument_transferDocumentRequestSourceSystem = null;
        _transferDocument_transferDocumentRequest.setSourceSystem(_transferDocument_transferDocumentRequestSourceSystem);
        datacontracts.core.documentservice.chubb._2016._03.TransferDocumentResponse _transferDocument__return = port.transferDocument(_transferDocument_transferDocumentRequest);
        System.out.println("transferDocument.result=" + _transferDocument__return);


        }

        System.exit(0);
    }

}
