
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package core.documentservice.chubb;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-22T11:12:47.839+01:00
 * Generated source version: 3.3.3
 *
 */

@javax.jws.WebService(
                      serviceName = "Document",
                      portName = "wsHttpEndpoint",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "https://uk01deca021.aceins.com:4466/DocumentService.svc?wsdl",
                      endpointInterface = "core.documentservice.chubb.IDocument")

public class WsHttpEndpointImpl implements IDocument {

    private static final Logger LOG = Logger.getLogger(WsHttpEndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see core.documentservice.chubb.IDocument#transferDocument(datacontracts.core.documentservice.chubb._2016._03.TransferDocumentRequest transferDocumentRequest)*
     */
    public datacontracts.core.documentservice.chubb._2016._03.TransferDocumentResponse transferDocument(datacontracts.core.documentservice.chubb._2016._03.TransferDocumentRequest transferDocumentRequest) {
        LOG.info("Executing operation transferDocument");
        System.out.println(transferDocumentRequest);
        try {
            datacontracts.core.documentservice.chubb._2016._03.TransferDocumentResponse _return = new datacontracts.core.documentservice.chubb._2016._03.TransferDocumentResponse();
            javax.xml.bind.JAXBElement<datacontracts.core.documentservice.chubb._2016._03.TransferDocumentResponse.OutPutReferenceData> _returnOutPutReferenceData = null;
            _return.setOutPutReferenceData(_returnOutPutReferenceData);
            _return.setOverallResult(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
