//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.20 at 07:29:42 AM BST 
//


package com.chubb.preprocessors.emailbrokermaster.jaxb.iccxml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PackageID"/>
 *         &lt;element ref="{}Otherref"/>
 *         &lt;element ref="{}IsParent"/>
 *         &lt;element ref="{}FileName"/>
 *         &lt;element ref="{}scan_info"/>
 *         &lt;element ref="{}scandate"/>
 *         &lt;element ref="{}scantime"/>
 *         &lt;element ref="{}doc_description"/>
 *         &lt;element ref="{}file_type_code"/>
 *         &lt;element ref="{}folder_type_code"/>
 *         &lt;element ref="{}doc_type_code"/>
 *         &lt;element ref="{}Docdate"/>
 *         &lt;element ref="{}doc_producer"/>
 *         &lt;element ref="{}AIN"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "packageID",
        "otherref",
        "isParent",
        "fileName",
        "scanInfo",
        "scandate",
        "scantime",
        "docDescription",
        "fileTypeCode",
        "folderTypeCode",
        "docTypeCode",
        "docdate",
        "docProducer",
        "ain"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElement(name = "PackageID", required = true)
    protected String packageID;
    @XmlElement(name = "Otherref", required = true)
    protected String otherref;
    @XmlElement(name = "IsParent")
    protected String isParent;
    @XmlElement(name = "FileName", required = true)
    protected String fileName;
    @XmlElement(name = "scan_info", required = true)
    protected String scanInfo;
    @XmlElement(required = true)
    protected String scandate;
    @XmlElement(required = true)
    protected String scantime;
    @XmlElement(name = "doc_description", required = true)
    protected String docDescription;
    @XmlElement(name = "file_type_code", required = true)
    protected String fileTypeCode;
    @XmlElement(name = "folder_type_code", required = true)
    protected String folderTypeCode;
    @XmlElement(name = "doc_type_code", required = true)
    protected String docTypeCode;
    @XmlElement(name = "Docdate", required = true)
    protected String docdate;
    @XmlElement(name = "doc_producer", required = true)
    protected String docProducer;
    @XmlElement(name = "AIN", required = true)
    protected String ain;

    /**
     * Gets the value of the packageID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPackageID() {
        return packageID;
    }

    /**
     * Sets the value of the packageID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPackageID(String value) {
        this.packageID = value;
    }

    /**
     * Gets the value of the otherref property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOtherref() {
        return otherref;
    }

    /**
     * Sets the value of the otherref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOtherref(String value) {
        this.otherref = value;
    }

    /**
     * Gets the value of the isParent property.
     */
    public String isIsParent() {
        return isParent;
    }

    /**
     * Sets the value of the isParent property.
     */
    public void setIsParent(String value) {
        this.isParent = value;
    }

    /**
     * Gets the value of the fileName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the scanInfo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScanInfo() {
        return scanInfo;
    }

    /**
     * Sets the value of the scanInfo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScanInfo(String value) {
        this.scanInfo = value;
    }

    /**
     * Gets the value of the scandate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScandate() {
        return scandate;
    }

    /**
     * Sets the value of the scandate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScandate(String value) {
        this.scandate = value;
    }

    /**
     * Gets the value of the scantime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScantime() {
        return scantime;
    }

    /**
     * Sets the value of the scantime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScantime(String value) {
        this.scantime = value;
    }

    /**
     * Gets the value of the docDescription property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocDescription() {
        return docDescription;
    }

    /**
     * Sets the value of the docDescription property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocDescription(String value) {
        this.docDescription = value;
    }

    /**
     * Gets the value of the fileTypeCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFileTypeCode() {
        return fileTypeCode;
    }

    /**
     * Sets the value of the fileTypeCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFileTypeCode(String value) {
        this.fileTypeCode = value;
    }

    /**
     * Gets the value of the folderTypeCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFolderTypeCode() {
        return folderTypeCode;
    }

    /**
     * Sets the value of the folderTypeCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFolderTypeCode(String value) {
        this.folderTypeCode = value;
    }

    /**
     * Gets the value of the docTypeCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocTypeCode() {
        return docTypeCode;
    }

    /**
     * Sets the value of the docTypeCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocTypeCode(String value) {
        this.docTypeCode = value;
    }

    /**
     * Gets the value of the docdate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocdate() {
        return docdate;
    }

    /**
     * Sets the value of the docdate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocdate(String value) {
        this.docdate = value;
    }

    /**
     * Gets the value of the docProducer property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocProducer() {
        return docProducer;
    }

    /**
     * Sets the value of the docProducer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocProducer(String value) {
        this.docProducer = value;
    }

    /**
     * Gets the value of the ain property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAIN() {
        return ain;
    }

    /**
     * Sets the value of the ain property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAIN(String value) {
        this.ain = value;
    }

}
