//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.20 at 07:29:42 AM BST 
//


package com.chubb.preprocessors.emailbrokermaster.jaxb.iccxml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Subject"/>
 *         &lt;element ref="{}ToMailAddress"/>
 *         &lt;element ref="{}FromMailAddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "subject",
        "toMailAddress",
        "fromMailAddress"
})
@XmlRootElement(name = "Email_Metadata")
public class EmailMetadata {

    @XmlElement(name = "Subject", required = true)
    protected String subject;
    @XmlElement(name = "ToMailAddress", required = true)
    protected String toMailAddress;
    @XmlElement(name = "FromMailAddress", required = true)
    protected String fromMailAddress;

    /**
     * Gets the value of the subject property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the toMailAddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getToMailAddress() {
        return toMailAddress;
    }

    /**
     * Sets the value of the toMailAddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setToMailAddress(String value) {
        this.toMailAddress = value;
    }

    /**
     * Gets the value of the fromMailAddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFromMailAddress() {
        return fromMailAddress;
    }

    /**
     * Sets the value of the fromMailAddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFromMailAddress(String value) {
        this.fromMailAddress = value;
    }

}
