//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.20 at 07:29:42 AM BST 
//


package com.chubb.preprocessors.emailbrokermaster.jaxb.iccxml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Email_Metadata"/>
 *         &lt;element ref="{}workbasket_data"/>
 *         &lt;element ref="{}Index"/>
 *         &lt;element ref="{}Document"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "emailMetadata",
        "workbasketData",
        "index",
        "document"
})
@XmlRootElement(name = "ScannedImage")
public class ScannedImage {

    @XmlElement(name = "Email_Metadata", required = true)
    protected EmailMetadata emailMetadata;
    @XmlElement(name = "workbasket_data", required = true)
    protected WorkbasketData workbasketData;
    @XmlElement(name = "Index", required = true)
    protected Index index;
    @XmlElement(name = "Document", required = true)
    protected Document document;

    /**
     * Gets the value of the emailMetadata property.
     *
     * @return possible object is
     * {@link EmailMetadata }
     */
    public EmailMetadata getEmailMetadata() {
        return emailMetadata;
    }

    /**
     * Sets the value of the emailMetadata property.
     *
     * @param value allowed object is
     *              {@link EmailMetadata }
     */
    public void setEmailMetadata(EmailMetadata value) {
        this.emailMetadata = value;
    }

    /**
     * Gets the value of the workbasketData property.
     *
     * @return possible object is
     * {@link WorkbasketData }
     */
    public WorkbasketData getWorkbasketData() {
        return workbasketData;
    }

    /**
     * Sets the value of the workbasketData property.
     *
     * @param value allowed object is
     *              {@link WorkbasketData }
     */
    public void setWorkbasketData(WorkbasketData value) {
        this.workbasketData = value;
    }

    /**
     * Gets the value of the index property.
     *
     * @return possible object is
     * {@link Index }
     */
    public Index getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     *
     * @param value allowed object is
     *              {@link Index }
     */
    public void setIndex(Index value) {
        this.index = value;
    }

    /**
     * Gets the value of the document property.
     *
     * @return possible object is
     * {@link Document }
     */
    public Document getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     *
     * @param value allowed object is
     *              {@link Document }
     */
    public void setDocument(Document value) {
        this.document = value;
    }

}
