package com.chubb.workview.documentservice._2016._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-08T13:38:24.834+01:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", name = "DocumentService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.chubb.workview.documentservice.ObjectFactory.class})
public interface DocumentService {

    @WebMethod(operationName = "ExecuteDocumentMove", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExecuteDocumentMove")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExecuteDocumentMove", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExecuteDocumentMoveResponse")
    @RequestWrapper(localName = "ExecuteDocumentMove", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ExecuteDocumentMove")
    @ResponseWrapper(localName = "ExecuteDocumentMoveResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ExecuteDocumentMoveResponse")
    @WebResult(name = "ExecuteDocumentMoveResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.DocumentMoveResponse executeDocumentMove(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.DocumentMoveRequest request
    );

    @WebMethod(operationName = "GetDocumentDetails", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetDocumentDetails")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetDocumentDetails", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetDocumentDetailsResponse")
    @RequestWrapper(localName = "GetDocumentDetails", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.GetDocumentDetails")
    @ResponseWrapper(localName = "GetDocumentDetailsResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.GetDocumentDetailsResponse")
    @WebResult(name = "GetDocumentDetailsResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.DocumentDetailsResponse getDocumentDetails(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.DocumentDetailsRequest request
    );

    @WebMethod(operationName = "DocumentLifeCycleStatusUpdate", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/DocumentLifeCycleStatusUpdate")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/DocumentLifeCycleStatusUpdate", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/DocumentLifeCycleStatusUpdateResponse")
    @RequestWrapper(localName = "DocumentLifeCycleStatusUpdate", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.DocumentLifeCycleStatusUpdate")
    @ResponseWrapper(localName = "DocumentLifeCycleStatusUpdateResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.DocumentLifeCycleStatusUpdateResponse")
    @WebResult(name = "DocumentLifeCycleStatusUpdateResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.StatusUpdateResponse documentLifeCycleStatusUpdate(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.StatusUpdateRequest request
    );

    @WebMethod(operationName = "ExportDocument", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExportDocument")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExportDocument", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExportDocumentResponse")
    @RequestWrapper(localName = "ExportDocument", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ExportDocument")
    @ResponseWrapper(localName = "ExportDocumentResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ExportDocumentResponse")
    @WebResult(name = "ExportDocumentResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.DocumentResponse exportDocument(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.DocumentRequest request
    );

    @WebMethod(operationName = "ImportDocumentToFile", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ImportDocumentToFile")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ImportDocumentToFile", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ImportDocumentToFileResponse")
    @RequestWrapper(localName = "ImportDocumentToFile", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ImportDocumentToFile")
    @ResponseWrapper(localName = "ImportDocumentToFileResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ImportDocumentToFileResponse")
    @WebResult(name = "ImportDocumentToFileResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.ImportDocumentToFileResponse importDocumentToFile(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.ImportDocumentToFileRequest request
    );

    @WebMethod(operationName = "GetSpecificDocument", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetSpecificDocument")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetSpecificDocument", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetSpecificDocumentResponse")
    @RequestWrapper(localName = "GetSpecificDocument", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.GetSpecificDocument")
    @ResponseWrapper(localName = "GetSpecificDocumentResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.GetSpecificDocumentResponse")
    @WebResult(name = "GetSpecificDocumentResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.SpecificDocumentResponse getSpecificDocument(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.SpecificDocumentRequest request
    );

    @WebMethod(operationName = "UpdateDocumentDetails", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/UpdateDocumentDetails")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/UpdateDocumentDetails", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/UpdateDocumentDetailsResponse")
    @RequestWrapper(localName = "UpdateDocumentDetails", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.UpdateDocumentDetails")
    @ResponseWrapper(localName = "UpdateDocumentDetailsResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.UpdateDocumentDetailsResponse")
    @WebResult(name = "UpdateDocumentDetailsResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.UpdateDocumentDetailsResponse updateDocumentDetails(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.UpdateDocumentDetailsRequest request
    );

    @WebMethod(operationName = "ExecuteIndexDocument", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExecuteIndexDocument")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExecuteIndexDocument", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ExecuteIndexDocumentResponse")
    @RequestWrapper(localName = "ExecuteIndexDocument", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ExecuteIndexDocument")
    @ResponseWrapper(localName = "ExecuteIndexDocumentResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ExecuteIndexDocumentResponse")
    @WebResult(name = "ExecuteIndexDocumentResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.IndexDocumentResponse executeIndexDocument(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.IndexDocumentRequest request
    );

    @WebMethod(operationName = "ImportandIndexDocument", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ImportandIndexDocument")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ImportandIndexDocument", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/ImportandIndexDocumentResponse")
    @RequestWrapper(localName = "ImportandIndexDocument", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ImportandIndexDocument")
    @ResponseWrapper(localName = "ImportandIndexDocumentResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.ImportandIndexDocumentResponse")
    @WebResult(name = "ImportandIndexDocumentResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.ImportandIndexDocumentResponseInfo importandIndexDocument(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.ImportandIndexDocumentRequest request
    );

    @WebMethod(operationName = "GetDocumentInformation", action = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetDocumentInformation")
    @Action(input = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetDocumentInformation", output = "http://chubb.com/Workview/DocumentService/2016/06/DocumentService/GetDocumentInformationResponse")
    @RequestWrapper(localName = "GetDocumentInformation", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.GetDocumentInformation")
    @ResponseWrapper(localName = "GetDocumentInformationResponse", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06", className = "com.chubb.workview.documentservice._2016._06.GetDocumentInformationResponse")
    @WebResult(name = "GetDocumentInformationResult", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
    public com.chubb.workview.documentservice.DocumentInformationResponse getDocumentInformation(

        @WebParam(name = "request", targetNamespace = "http://chubb.com/Workview/DocumentService/2016/06")
        com.chubb.workview.documentservice.DocumentInformationRequest request
    );
}
