
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.chubb.workview.documentservice._2016._06;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-08T13:38:24.751+01:00
 * Generated source version: 3.3.3
 *
 */

@javax.jws.WebService(
                      serviceName = "DocumentService",
                      portName = "wsHttpEndpoint",
                      targetNamespace = "http://chubb.com/WorkView/DocumentService/2016/06",
                      wsdlLocation = "https://wvuat-cogr2-iws-446.aceins.com:446/Workview/DocumentService/DocumentService.svc?wsdl",
                      endpointInterface = "com.chubb.workview.documentservice._2016._06.DocumentService")

public class WsHttpEndpointImpl implements DocumentService {

    private static final Logger LOG = Logger.getLogger(WsHttpEndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#executeDocumentMove(com.chubb.workview.documentservice.DocumentMoveRequest request)*
     */
    public com.chubb.workview.documentservice.DocumentMoveResponse executeDocumentMove(com.chubb.workview.documentservice.DocumentMoveRequest request) {
        LOG.info("Executing operation executeDocumentMove");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.DocumentMoveResponse _return = new com.chubb.workview.documentservice.DocumentMoveResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(false));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnResult = null;
            _return.setResult(_returnResult);
            _return.setNoteDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-10-08T13:38:24.812+01:00"));
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentGUID = null;
            _return.setDocumentGUID(_returnDocumentGUID);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#getDocumentDetails(com.chubb.workview.documentservice.DocumentDetailsRequest request)*
     */
    public com.chubb.workview.documentservice.DocumentDetailsResponse getDocumentDetails(com.chubb.workview.documentservice.DocumentDetailsRequest request) {
        LOG.info("Executing operation getDocumentDetails");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.DocumentDetailsResponse _return = new com.chubb.workview.documentservice.DocumentDetailsResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(false));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnResult = null;
            _return.setResult(_returnResult);
            javax.xml.bind.JAXBElement<com.chubb.workview.documentservice.ArrayOfWVDocument> _returnWorkViewDocuments = null;
            _return.setWorkViewDocuments(_returnWorkViewDocuments);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#documentLifeCycleStatusUpdate(com.chubb.workview.documentservice.StatusUpdateRequest request)*
     */
    public com.chubb.workview.documentservice.StatusUpdateResponse documentLifeCycleStatusUpdate(com.chubb.workview.documentservice.StatusUpdateRequest request) {
        LOG.info("Executing operation documentLifeCycleStatusUpdate");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.StatusUpdateResponse _return = new com.chubb.workview.documentservice.StatusUpdateResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            com.chubb.workview.documentservice.ArrayOfDocStatusInfo _returnDocumentsStatusInfo = new com.chubb.workview.documentservice.ArrayOfDocStatusInfo();
            java.util.List<com.chubb.workview.documentservice.DocStatusInfo> _returnDocumentsStatusInfoDocStatusInfo = new java.util.ArrayList<com.chubb.workview.documentservice.DocStatusInfo>();
            com.chubb.workview.documentservice.DocStatusInfo _returnDocumentsStatusInfoDocStatusInfoVal1 = new com.chubb.workview.documentservice.DocStatusInfo();
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentsStatusInfoDocStatusInfoVal1DocumentGUID = null;
            _returnDocumentsStatusInfoDocStatusInfoVal1.setDocumentGUID(_returnDocumentsStatusInfoDocStatusInfoVal1DocumentGUID);
            _returnDocumentsStatusInfoDocStatusInfoVal1.setStatus(Boolean.valueOf(false));
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentsStatusInfoDocStatusInfoVal1ErrorText = null;
            _returnDocumentsStatusInfoDocStatusInfoVal1.setErrorText(_returnDocumentsStatusInfoDocStatusInfoVal1ErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentsStatusInfoDocStatusInfoVal1Result = null;
            _returnDocumentsStatusInfoDocStatusInfoVal1.setResult(_returnDocumentsStatusInfoDocStatusInfoVal1Result);
            _returnDocumentsStatusInfoDocStatusInfo.add(_returnDocumentsStatusInfoDocStatusInfoVal1);
            _returnDocumentsStatusInfo.getDocStatusInfo().addAll(_returnDocumentsStatusInfoDocStatusInfo);
            _return.setDocumentsStatusInfo(_returnDocumentsStatusInfo);
            com.chubb.workview.documentservice.EnvironmentData _returnEnvironmentData = new com.chubb.workview.documentservice.EnvironmentData();
            _returnEnvironmentData.setMessageGUID("MessageGUID-1676290474");
            _returnEnvironmentData.setCountryCode("CountryCode180996190");
            _returnEnvironmentData.setSourceSystem("SourceSystem1282952360");
            _returnEnvironmentData.setWorkViewLogonID("WorkViewLogonID774022594");
            _returnEnvironmentData.setWorkViewEnvironment("WorkViewEnvironment-2132892601");
            _return.setEnvironmentData(_returnEnvironmentData);
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#exportDocument(com.chubb.workview.documentservice.DocumentRequest request)*
     */
    public com.chubb.workview.documentservice.DocumentResponse exportDocument(com.chubb.workview.documentservice.DocumentRequest request) {
        LOG.info("Executing operation exportDocument");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.DocumentResponse _return = new com.chubb.workview.documentservice.DocumentResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(false));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentLifeCycleStatusId = null;
            _return.setDocumentLifeCycleStatusId(_returnDocumentLifeCycleStatusId);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#importDocumentToFile(com.chubb.workview.documentservice.ImportDocumentToFileRequest request)*
     */
    public com.chubb.workview.documentservice.ImportDocumentToFileResponse importDocumentToFile(com.chubb.workview.documentservice.ImportDocumentToFileRequest request) {
        LOG.info("Executing operation importDocumentToFile");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.ImportDocumentToFileResponse _return = new com.chubb.workview.documentservice.ImportDocumentToFileResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(false));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnResult = null;
            _return.setResult(_returnResult);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentGUID = null;
            _return.setDocumentGUID(_returnDocumentGUID);
            javax.xml.bind.JAXBElement<java.lang.String> _returnFileNumber = null;
            _return.setFileNumber(_returnFileNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnFileTypeCode = null;
            _return.setFileTypeCode(_returnFileTypeCode);
            javax.xml.bind.JAXBElement<java.lang.String> _returnFileTypeDescription = null;
            _return.setFileTypeDescription(_returnFileTypeDescription);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentDescription = null;
            _return.setDocumentDescription(_returnDocumentDescription);
            javax.xml.bind.JAXBElement<java.lang.String> _returnSecurityPolicyID = null;
            _return.setSecurityPolicyID(_returnSecurityPolicyID);
            javax.xml.bind.JAXBElement<com.chubb.workview.documentservice.ArrayOfAttachmentInfo> _returnAttachmentsInfo = null;
            _return.setAttachmentsInfo(_returnAttachmentsInfo);
            javax.xml.bind.JAXBElement<java.lang.String> _returnCaseGUID = null;
            _return.setCaseGUID(_returnCaseGUID);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#getSpecificDocument(com.chubb.workview.documentservice.SpecificDocumentRequest request)*
     */
    public com.chubb.workview.documentservice.SpecificDocumentResponse getSpecificDocument(com.chubb.workview.documentservice.SpecificDocumentRequest request) {
        LOG.info("Executing operation getSpecificDocument");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.SpecificDocumentResponse _return = new com.chubb.workview.documentservice.SpecificDocumentResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(false));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<com.chubb.workview.documentservice.WorkViewDocument> _returnWorkViewDocument = null;
            _return.setWorkViewDocument(_returnWorkViewDocument);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#updateDocumentDetails(com.chubb.workview.documentservice.UpdateDocumentDetailsRequest request)*
     */
    public com.chubb.workview.documentservice.UpdateDocumentDetailsResponse updateDocumentDetails(com.chubb.workview.documentservice.UpdateDocumentDetailsRequest request) {
        LOG.info("Executing operation updateDocumentDetails");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.UpdateDocumentDetailsResponse _return = new com.chubb.workview.documentservice.UpdateDocumentDetailsResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(false));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnResult = null;
            _return.setResult(_returnResult);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentGUID = null;
            _return.setDocumentGUID(_returnDocumentGUID);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#executeIndexDocument(com.chubb.workview.documentservice.IndexDocumentRequest request)*
     */
    public com.chubb.workview.documentservice.IndexDocumentResponse executeIndexDocument(com.chubb.workview.documentservice.IndexDocumentRequest request) {
        LOG.info("Executing operation executeIndexDocument");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.IndexDocumentResponse _return = new com.chubb.workview.documentservice.IndexDocumentResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(true));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnResult = null;
            _return.setResult(_returnResult);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentGUID = null;
            _return.setDocumentGUID(_returnDocumentGUID);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#importandIndexDocument(com.chubb.workview.documentservice.ImportandIndexDocumentRequest request)*
     */
    public com.chubb.workview.documentservice.ImportandIndexDocumentResponseInfo importandIndexDocument(com.chubb.workview.documentservice.ImportandIndexDocumentRequest request) {
        LOG.info("Executing operation importandIndexDocument");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.ImportandIndexDocumentResponseInfo _return = new com.chubb.workview.documentservice.ImportandIndexDocumentResponseInfo();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            _return.setStatus(Boolean.valueOf(true));
            javax.xml.bind.JAXBElement<java.lang.String> _returnErrorText = null;
            _return.setErrorText(_returnErrorText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnResult = null;
            _return.setResult(_returnResult);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentGUID = null;
            _return.setDocumentGUID(_returnDocumentGUID);
            javax.xml.bind.JAXBElement<java.lang.String> _returnPolicyNumber = null;
            _return.setPolicyNumber(_returnPolicyNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnCertificateNumber = null;
            _return.setCertificateNumber(_returnCertificateNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnClaimNumber = null;
            _return.setClaimNumber(_returnClaimNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnDocumentDescription = null;
            _return.setDocumentDescription(_returnDocumentDescription);
            javax.xml.bind.JAXBElement<java.lang.String> _returnSecurityPolicyID = null;
            _return.setSecurityPolicyID(_returnSecurityPolicyID);
            javax.xml.bind.JAXBElement<com.chubb.workview.documentservice.ArrayOfAttachmentInfo> _returnAttachmentsInfo = null;
            _return.setAttachmentsInfo(_returnAttachmentsInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chubb.workview.documentservice._2016._06.DocumentService#getDocumentInformation(com.chubb.workview.documentservice.DocumentInformationRequest request)*
     */
    public com.chubb.workview.documentservice.DocumentInformationResponse getDocumentInformation(com.chubb.workview.documentservice.DocumentInformationRequest request) {
        LOG.info("Executing operation getDocumentInformation");
        System.out.println(request);
        try {
            com.chubb.workview.documentservice.DocumentInformationResponse _return = new com.chubb.workview.documentservice.DocumentInformationResponse();
            javax.xml.bind.JAXBElement<java.lang.String> _returnOverallResult = null;
            _return.setOverallResult(_returnOverallResult);
            javax.xml.bind.JAXBElement<com.chubb.workview.documentservice.ArrayOfDocInfoResponse> _returnDocumentInformationResponse = null;
            _return.setDocumentInformationResponse(_returnDocumentInformationResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
