
package com.chubb.workview.certificateservice._2016._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CertificateService", targetNamespace = "http://Chubb.com/WorkView/CertificateService/2016/06")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CertificateService {


    /**
     * 
     * @param request
     * @return
     *     returns com.chubb.workview.preprocessors.generated.certificateservice.Response
     */
    @WebMethod(operationName = "CreateOrUpdateCertificate", action = "CreateOrUpdateCertificate")
    @WebResult(name = "CreateOrUpdateCertificateResult", targetNamespace = "http://Chubb.com/WorkView/CertificateService/2016/06")
    @RequestWrapper(localName = "CreateOrUpdateCertificate", targetNamespace = "http://Chubb.com/WorkView/CertificateService/2016/06", className = "com.chubb.workview.certificateservice._2016._06.certificateservice.CreateOrUpdateCertificate")
    @ResponseWrapper(localName = "CreateOrUpdateCertificateResponse", targetNamespace = "http://Chubb.com/WorkView/CertificateService/2016/06", className = "com.chubb.workview.certificateservice._2016._06.CreateOrUpdateCertificateResponse")
    public Response createOrUpdateCertificate(
        @WebParam(name = "request", targetNamespace = "http://Chubb.com/WorkView/CertificateService/2016/06")
        Request request);

}
