package com.chubb.workview.checksum;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IService1 {


    /**
     * @param filename
     * @param directoryName
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Validation", action = "http://tempuri.org/IService1/Validation")
    @WebResult(name = "ValidationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Validation", targetNamespace = "http://tempuri.org/", className = "com.chubb.workview.Checksum.Validation")
    @ResponseWrapper(localName = "ValidationResponse", targetNamespace = "http://tempuri.org/", className = "com.chubb.workview.Checksum.ValidationResponse")
    public String validation(
            @WebParam(name = "DirectoryName", targetNamespace = "http://tempuri.org/")
                    String directoryName,
            @WebParam(name = "Filename", targetNamespace = "http://tempuri.org/")
                    String filename);

}
