//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.01 at 05:13:04 AM GMT 
//


package com.chubb.preprocessors.emailbrokermaster.jaxb.Indexxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}scan_info"/&gt;
 *         &lt;element ref="{}doc_description"/&gt;
 *         &lt;element ref="{}ftyp_code"/&gt;
 *         &lt;element ref="{}doc_typ_code"/&gt;
 *         &lt;element ref="{}doc_producer"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "document")
public class Document {

    @XmlElement(name = "scan_info", required = true)
    protected String scanInfo;
    @XmlElement(name = "doc_description", required = true)
    protected String docDescription;
    @XmlElement(name = "ftyp_code", required = true)
    protected String ftypCode;
    @XmlElement(name = "doc_typ_code", required = true)
    protected String docTypCode;
    @XmlElement(name = "doc_producer", required = true)
    protected String docProducer;

    /**
     * Gets the value of the scanInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScanInfo() {
        return scanInfo;
    }

    /**
     * Sets the value of the scanInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScanInfo(String value) {
        this.scanInfo = value;
    }

    /**
     * Gets the value of the docDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocDescription() {
        return docDescription;
    }

    /**
     * Sets the value of the docDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocDescription(String value) {
        this.docDescription = value;
    }

    /**
     * Gets the value of the ftypCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtypCode() {
        return ftypCode;
    }

    /**
     * Sets the value of the ftypCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtypCode(String value) {
        this.ftypCode = value;
    }

    /**
     * Gets the value of the docTypCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocTypCode() {
        return docTypCode;
    }

    /**
     * Sets the value of the docTypCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocTypCode(String value) {
        this.docTypCode = value;
    }

    /**
     * Gets the value of the docProducer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocProducer() {
        return docProducer;
    }

    /**
     * Sets the value of the docProducer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocProducer(String value) {
        this.docProducer = value;
    }

}
