//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.28 at 12:33:03 PM GMT 
//


package com.chubb.preprocessors.emailbrokermaster.jaxb.Indexxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bpu_code" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="queue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="document"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="scan_info" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ftyp_code" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="doc_typ_code" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="doc_producer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="doc_description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bpuCode",
    "queue",
    "document"
})
@XmlRootElement(name = "index_envelope")
public class IndexEnvelope {

    @XmlElement(name = "bpu_code")
    protected int bpuCode;
    @XmlElement(required = true)
    protected String queue;
    @XmlElement(required = true)
    protected IndexEnvelope.Document document;

    /**
     * Gets the value of the bpuCode property.
     * 
     */
    public int getBpuCode() {
        return bpuCode;
    }

    /**
     * Sets the value of the bpuCode property.
     * 
     */
    public void setBpuCode(int value) {
        this.bpuCode = value;
    }

    /**
     * Gets the value of the queue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueue() {
        return queue;
    }

    /**
     * Sets the value of the queue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueue(String value) {
        this.queue = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link IndexEnvelope.Document }
     *     
     */
    public IndexEnvelope.Document getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexEnvelope.Document }
     *     
     */
    public void setDocument(IndexEnvelope.Document value) {
        this.document = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="scan_info" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ftyp_code" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="doc_typ_code" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="doc_producer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="doc_description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scanInfo",
        "ftypCode",
        "docTypCode",
        "docProducer",
        "docDescription"
    })
    public static class Document {

        @XmlElement(name = "scan_info", required = true)
        protected String scanInfo;
        @XmlElement(name = "ftyp_code")
        protected int ftypCode;
        @XmlElement(name = "doc_typ_code")
        protected int docTypCode;
        @XmlElement(name = "doc_producer", required = true)
        protected String docProducer;
        @XmlElement(name = "doc_description", required = true)
        protected String docDescription;

        /**
         * Gets the value of the scanInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScanInfo() {
            return scanInfo;
        }

        /**
         * Sets the value of the scanInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScanInfo(String value) {
            this.scanInfo = value;
        }

        /**
         * Gets the value of the ftypCode property.
         * 
         */
        public int getFtypCode() {
            return ftypCode;
        }

        /**
         * Sets the value of the ftypCode property.
         * 
         */
        public void setFtypCode(int value) {
            this.ftypCode = value;
        }

        /**
         * Gets the value of the docTypCode property.
         * 
         */
        public int getDocTypCode() {
            return docTypCode;
        }

        /**
         * Sets the value of the docTypCode property.
         * 
         */
        public void setDocTypCode(int value) {
            this.docTypCode = value;
        }

        /**
         * Gets the value of the docProducer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocProducer() {
            return docProducer;
        }

        /**
         * Sets the value of the docProducer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocProducer(String value) {
            this.docProducer = value;
        }

        /**
         * Gets the value of the docDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocDescription() {
            return docDescription;
        }

        /**
         * Sets the value of the docDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocDescription(String value) {
            this.docDescription = value;
        }

    }

}
