//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.20 at 07:29:42 AM BST 
//


package com.chubb.preprocessors.emailbrokermaster.jaxb.iccxml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Error_Queue"/>
 *         &lt;element ref="{}WorkBasket_Code"/>
 *         &lt;element ref="{}Error_flag"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "errorQueue",
        "workBasketCode",
        "errorFlag"
})
@XmlRootElement(name = "workbasket_data")
public class WorkbasketData {

    @XmlElement(name = "Error_Queue", required = true)
    protected String errorQueue;
    @XmlElement(name = "WorkBasket_Code", required = true)
    protected String workBasketCode;
    @XmlElement(name = "Error_flag", required = true)
    protected String errorFlag;

    /**
     * Gets the value of the errorQueue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getErrorQueue() {
        return errorQueue;
    }

    /**
     * Sets the value of the errorQueue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setErrorQueue(String value) {
        this.errorQueue = value;
    }

    /**
     * Gets the value of the workBasketCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWorkBasketCode() {
        return workBasketCode;
    }

    /**
     * Sets the value of the workBasketCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWorkBasketCode(String value) {
        this.workBasketCode = value;
    }

    /**
     * Gets the value of the errorFlag property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getErrorFlag() {
        return errorFlag;
    }

    /**
     * Sets the value of the errorFlag property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setErrorFlag(String value) {
        this.errorFlag = value;
    }

}
