
package com.chubb.workview.generalfileservice._2016._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GeneralFile", targetNamespace = "http://Chubb.com/WorkView/GeneralFile/2016/06")
@XmlSeeAlso({
    ObjectFactory.class,
   
})
public interface GeneralFile {


    /**
     * 
     * @param request
     * @return
     *     returns com.chubb.workview.generalfile._2016._06.Response
     */
    @WebMethod(operationName = "CreateOrUpdateGeneralFile", action = "http://Chubb.com/WorkView/GeneralFile/2016/06/GeneralFile/CreateOrUpdateGeneralFile")
    @WebResult(name = "CreateOrUpdateGeneralFileResult", targetNamespace = "http://Chubb.com/WorkView/GeneralFile/2016/06")
    @RequestWrapper(localName = "CreateOrUpdateGeneralFile", targetNamespace = "http://Chubb.com/WorkView/GeneralFile/2016/06", className = "com.chubb.workview.generalfile._2016._06.CreateOrUpdateGeneralFile")
    @ResponseWrapper(localName = "CreateOrUpdateGeneralFileResponse", targetNamespace = "http://Chubb.com/WorkView/GeneralFile/2016/06", className = "com.chubb.workview.generalfile._2016._06.CreateOrUpdateGeneralFileResponse")
    public Response createOrUpdateGeneralFile(
        @WebParam(name = "request", targetNamespace = "http://Chubb.com/WorkView/GeneralFile/2016/06")
        Request request);

}
